import jsPDF from "jspdf";
import "jspdf-autotable";
import { toast } from "sonner";

export function exportToCSV(filename: string, headers: string[], data: any[]) {
  const csvContent = [
    headers.join(","),
    ...data.map((row) =>
      headers
        .map((h) => {
          const val = row[h] !== undefined && row[h] !== null ? String(row[h]) : "";
          return `"${val.replace(/"/g, '""')}"`;
        })
        .join(",")
    ),
  ].join("\n");

  const blob = new Blob([csvContent], { type: "text/csv;charset=utf-8;" });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.setAttribute("href", url);
  link.setAttribute("download", `${filename}_${new Date().toISOString().split("T")[0]}.csv`);
  link.style.visibility = "hidden";
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);

  toast.success("CSV Export Successful", {
    description: `${filename} has been saved.`,
  });
}

export function exportToExcel(filename: string, headers: string[], data: any[]) {
  try {
    const importXlsx = require("xlsx"); // lazy load to avoid server-side issues
    const worksheet = importXlsx.utils.json_to_sheet(data.map(row => {
      let newRow: any = {};
      headers.forEach(h => newRow[h] = row[h]);
      return newRow;
    }));
    
    // Add header styling if possible (basic xlsx doesn't support complex styling without xlsx-js-style, but we preserve tables)
    const workbook = importXlsx.utils.book_new();
    importXlsx.utils.book_append_sheet(workbook, worksheet, "Report");
    importXlsx.writeFile(workbook, `${filename}_${new Date().toISOString().split("T")[0]}.xlsx`);
    
    toast.success("Excel Export Successful", {
      description: `${filename} has been saved.`,
    });
  } catch (error) {
    console.error("Excel Export failed:", error);
    toast.error("Excel Export Failed", {
      description: "An error occurred while generating the Excel file.",
    });
  }
}

export function exportToPDF(
  filename: string, 
  title: string, 
  headers: string[], 
  data: any[],
  options?: {
    dateRange?: string;
    generatedBy?: string;
    summary?: string;
  }
) {
  try {
    const doc = new jsPDF("landscape");

    // Header Section
    doc.setFontSize(22);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(33, 37, 41);
    doc.text("FOXFLOW ERP", 14, 20); // Company Name
    
    doc.setFontSize(14);
    doc.setFont("helvetica", "normal");
    doc.text(title, 14, 30); // Report Title

    // Metadata Section
    doc.setFontSize(10);
    doc.setTextColor(100, 100, 100);
    doc.text(`Date Range: ${options?.dateRange || "All Time"}`, 14, 40);
    doc.text(`Generated By: ${options?.generatedBy || "System User"}`, 14, 45);
    doc.text(`Generated Time: ${new Date().toLocaleString()}`, 14, 50);

    let startY = 60;
    
    // Summary Section
    if (options?.summary) {
      doc.setFontSize(11);
      doc.setTextColor(33, 37, 41);
      doc.setFont("helvetica", "italic");
      doc.text(`Summary: ${options.summary}`, 14, startY);
      startY += 10;
    }

    const bodyData = data.map((row) => headers.map((h) => row[h] !== undefined && row[h] !== null ? String(row[h]) : ""));

    // @ts-ignore
    doc.autoTable({
      startY: startY,
      head: [headers],
      body: bodyData,
      theme: "grid",
      styles: { fontSize: 8, cellPadding: 3 },
      headStyles: { fillColor: [41, 128, 185], textColor: 255, fontStyle: 'bold' },
      alternateRowStyles: { fillColor: [245, 245, 245] },
      didDrawPage: function (data: any) {
        // Page Numbers
        let str = "Page " + (doc.internal as any).getNumberOfPages();
        doc.setFontSize(10);
        const pageSize = doc.internal.pageSize;
        const pageHeight = pageSize.height ? pageSize.height : pageSize.getHeight();
        doc.text(str, data.settings.margin.left, pageHeight - 10);
      }
    });

    doc.save(`${filename}_${new Date().toISOString().split("T")[0]}.pdf`);
    toast.success("PDF Export Successful", {
      description: `${filename} has been saved.`,
    });
  } catch (error) {
    console.error("PDF Export failed:", error);
    toast.error("PDF Export Failed", {
      description: "An error occurred while generating the PDF.",
    });
  }
}

export function handlePrint() {
  window.print();
}
