import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import { toast } from "sonner";

export function exportToCSV(filename: string, headers: string[], data: any[]) {
  const csvContent = [
    headers.join(","),
    ...data.map((row) =>
      headers
        .map((h) => {
          const val = row[h] !== undefined && row[h] !== null ? String(row[h]) : "";
          return `"${val.replace(/"/g, '""')}"`;
        })
        .join(",")
    ),
  ].join("\n");

  const blob = new Blob([csvContent], { type: "text/csv;charset=utf-8;" });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.setAttribute("href", url);
  link.setAttribute("download", `${filename}_${new Date().toISOString().split("T")[0]}.csv`);
  link.style.visibility = "hidden";
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);

  toast.success("CSV Export Successful", {
    description: `${filename} has been saved.`,
  });
}

export function exportToExcel(filename: string, headers: string[], data: any[]) {
  try {
    const importXlsx = require("xlsx"); // lazy load to avoid server-side issues
    const worksheet = importXlsx.utils.json_to_sheet(data.map(row => {
      let newRow: any = {};
      headers.forEach(h => newRow[h] = row[h]);
      return newRow;
    }));
    
    // Add header styling if possible (basic xlsx doesn't support complex styling without xlsx-js-style, but we preserve tables)
    const workbook = importXlsx.utils.book_new();
    importXlsx.utils.book_append_sheet(workbook, worksheet, "Report");
    importXlsx.writeFile(workbook, `${filename}_${new Date().toISOString().split("T")[0]}.xlsx`);
    
    toast.success("Excel Export Successful", {
      description: `${filename} has been saved.`,
    });
  } catch (error) {
    console.error("Excel Export failed:", error);
    toast.error("Excel Export Failed", {
      description: "An error occurred while generating the Excel file.",
    });
  }
}

export function exportToPDF(
  filename: string, 
  title: string, 
  headers: string[], 
  data: any[],
  options?: {
    dateRange?: string;
    generatedBy?: string;
    oem?: string;
    dealer?: string;
    category?: string;
    status?: string;
    carrier?: string;
    filters?: Record<string, string>;
    summary?: string;
  }
) {
  try {
    const doc = new jsPDF("landscape");

    // Header Section
    doc.setFontSize(22);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(33, 37, 41);
    doc.text("FOXFLOW ERP", 14, 18); // Company Name
    
    doc.setFontSize(14);
    doc.setFont("helvetica", "normal");
    doc.text(title, 14, 27); // Report Title

    // Metadata Section
    doc.setFontSize(9);
    doc.setTextColor(90, 90, 90);
    
    let currentY = 36;
    doc.text(`Date Range: ${options?.dateRange || "All Time"}`, 14, currentY);
    currentY += 4.5;

    // Filter information
    const oemVal = options?.oem && options.oem !== "All" && options.oem !== "All OEMs" ? options.oem : null;
    if (oemVal) {
      doc.text(`OEM Filter: ${oemVal}`, 14, currentY);
      currentY += 4.5;
    }

    const dealerVal = options?.dealer && options.dealer !== "All" && options.dealer !== "All Dealers" ? options.dealer : null;
    if (dealerVal) {
      doc.text(`Dealer / Destination Filter: ${dealerVal}`, 14, currentY);
      currentY += 4.5;
    }

    const categoryVal = options?.category && options.category !== "All" && options.category !== "All Categories" ? options.category : null;
    if (categoryVal) {
      doc.text(`Category: ${categoryVal}`, 14, currentY);
      currentY += 4.5;
    }

    const statusVal = options?.status && options.status !== "All" && options.status !== "All Statuses" ? options.status : null;
    if (statusVal) {
      doc.text(`Status: ${statusVal}`, 14, currentY);
      currentY += 4.5;
    }

    const carrierVal = options?.carrier && options.carrier !== "All" && options.carrier !== "All Carriers" ? options.carrier : null;
    if (carrierVal) {
      doc.text(`Carrier: ${carrierVal}`, 14, currentY);
      currentY += 4.5;
    }

    if (options?.filters) {
      Object.entries(options.filters).forEach(([key, val]) => {
        if (val && val !== "All" && val !== "All Statuses" && val !== "All OEMs" && val !== "All Dealers") {
          doc.text(`${key}: ${val}`, 14, currentY);
          currentY += 4.5;
        }
      });
    }

    doc.text(`Generated By: ${options?.generatedBy || "System User"}`, 14, currentY);
    currentY += 4.5;
    doc.text(`Generated Time: ${new Date().toLocaleString()}`, 14, currentY);
    currentY += 6.5;

    let startY = currentY;
    
    // Summary Section
    if (options?.summary) {
      doc.setFontSize(10);
      doc.setTextColor(33, 37, 41);
      doc.setFont("helvetica", "italic");
      doc.text(`Summary: ${options.summary}`, 14, startY);
      startY += 7;
    }

    const bodyData = data.map((row) => headers.map((h) => row[h] !== undefined && row[h] !== null ? String(row[h]) : ""));

    autoTable(doc, {
      startY: startY,
      head: [headers],
      body: bodyData,
      theme: "grid",
      styles: { fontSize: 8, cellPadding: 3 },
      headStyles: { fillColor: [41, 128, 185], textColor: 255, fontStyle: 'bold' },
      alternateRowStyles: { fillColor: [245, 245, 245] },
      didDrawPage: function (data: any) {
        // Page Numbers
        let str = "Page " + (doc.internal as any).getNumberOfPages();
        doc.setFontSize(10);
        const pageSize = doc.internal.pageSize;
        const pageHeight = pageSize.height ? pageSize.height : pageSize.getHeight();
        doc.text(str, data.settings.margin.left, pageHeight - 10);
      }
    });

    doc.save(`${filename}_${new Date().toISOString().split("T")[0]}.pdf`);
    toast.success("PDF Export Successful", {
      description: `${filename} has been saved.`,
    });
  } catch (error) {
    console.error("PDF Export failed:", error);
    toast.error("PDF Export Failed", {
      description: "An error occurred while generating the PDF.",
    });
  }
}

export function handlePrint() {
  window.print();
}
